### ISSUE TITLE
pkgmeta embed

### ISSUE THREAD

**Issue by michaelnpsp** [EsreverWoW/LibThreatClassic#1]
Any tip on howto embed this library using a pkgmeta file (with no .toc file and no root directory) ?

**Comment by EsreverWoW** [comment]
I restructured the folder for you so that there's no root directory. The table of contents will still be there however.

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#2

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#3

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#4
