### ISSUE TITLE
Ace libraries optional dependencies, are not optional

### ISSUE THREAD

**Issue by michaelnpsp** [EsreverWoW/LibThreatClassic#2]
Its not possible to use the LibThreatClassic library without a lot of optional ace libraries installed.

**Comment by EsreverWoW** [comment]
They're not optional, but Ace3 is listed in OptionalDeps for load order, in case a user has installed it separately. If it is RequiredDeps, then it won't load unless Ace3 is present, even if it is in am embed somewhere else. See https://github.com/EsreverWoW/LibThreatClassic/blob/master/embeds.xml for what specific parts of Ace3 you'll need.

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#5
