### ISSUE TITLE
Paladin is attempt to perform arithmetic on local 'amt' (a string value)

### ISSUE THREAD

**Issue by NoobTaco** [EsreverWoW/LibThreatClassic#4]
On a paladin, after a fight or before engaging a fight it seems the library is causing other addons to fail.

Addons I have tested and receive the error below.
* ThreatPlates
* Details - with threat plugin
* ClassicThreat

I have tested each addon together and separately and after entering combat the error occurs.

`2x ...s\ThreatClassic-1.0-2\ClassModules\Classic\Paladin.lua:146: attempt to perform arithmetic on local 'amt' (a string value)
...s\ThreatClassic-1.0-2\ClassModules\Classic\Paladin.lua:146: in function `func'
...tes\Libs\ThreatClassic-1.0-2\ThreatClassModuleCore.lua:849: in function `calcBuffMods'
...tes\Libs\ThreatClassic-1.0-2\ThreatClassModuleCore.lua:1038: in function `?'
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>`

**Comment by EsreverWoW** [comment]
I may need additional information. What level is your Paladin? Have you learned Righteous Fury and/or Holy Shield? If so, do you only see this error when using one or both?

**Comment by NoobTaco** [comment]
He is level 20 and I only have Righteous Fury and have been using it. I can log in later to do some tests without it on.

**Comment by NoobTaco** [comment]
Just did some testing and it IS in fact when RF is active that the error is coming up. When it is off it is fine.

**Comment by EsreverWoW** [comment]
Closing this since this appears fixed.

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#7
