### ISSUE TITLE
Paladin Righteous Fury is ignored

### ISSUE THREAD

**Issue by twothe** [EsreverWoW/LibThreatClassic#5]
I just noticed that in the Paladin class module at line 133 where threat bonus is set when Righteous Fury is active, the value is set to the same value when that buff is gained and lost. I am pretty sure that is a bug.

		if action == "gain" or action == "exist" then
			rfOn = true
			self.isTanking = true
			self.passiveThreatModifiers = 1
		elseif action == "lose" then
			rfOn = false
			self.passiveThreatModifiers = 1
		end

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#8
