### ISSUE TITLE
Incorrect bit band check

### ISSUE THREAD

**Issue by MysticalOS** [EsreverWoW/LibThreatClassic#6]
bit_band(sourceFlags, COMBATLOG_OBJECT_TYPE_NPC) == COMBATLOG_OBJECT_TYPE_NPC

would never be true. you either want to check if it's equal to 0 or not equal to 0 as far as I can tell. this is basically seeing if bit band for sourceflags using COMBATLOG_OBJECT_TYPE_NPC is equal to COMBATLOG_OBJECT_TYPE_NPC, it wouldn't be.

Same problem with pet and player filters below it. This probably explains why none of the threat modifiers to abilities actually seem to be working right now.

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#9
