### ISSUE TITLE
Knock away does not correctly apply threat modifier

### ISSUE THREAD

**Issue by cannonpalms** [EsreverWoW/LibThreatClassic#7]
I see in your commit log that you recently made an attempt to fix Onyxia threat. However, I can confirm that in the current form of this library, Onyxia's Knock Away ability is still not working correctly. In addition to Onyxia's Knock Away, other Knock Away's are also not being handled correctly. No threat change seems to occur when the player is hit with Knock Away.

Details - TinyThreat utilizes this library, however in its previous version -- before https://github.com/EsreverWoW/LibThreatClassic/commit/aab88ebadc8bef562951f8404ac17389be216d1d . It also seems that TinyThreat is handling Knock Away correctly, which leads me to believe that this commit should be reverted. At the very least, more testing is required.

Thanks,
Cannon

EDIT: Updated title and comment to reflect that it is not just Onyxia's ability that is currently bugged, it is all Knock Aways.

**Comment by EsreverWoW** [comment]
I believe this is now fixed. Still need to add in handling for Onyxia's Fireball like we spoke about, but that is a separate issue which requires a bit more investigation.

**Comment by cannonpalms** [comment]
Issue migrated to cannonpalms/LibThreatClassic#10
